NOTE_PLAYED = 0
NOTE_OFF = 1
MIDI_START_SENT = 2
MIDI_STOP_SENT = 3

# game states #
RENDERER_INITIALISED = 10
QUIT = 11

# view states #
FULLSCREEN = 100
MASTER_TRACK_STATE_CHANGED = 110

PATTERN_TRACK_STATE_CHANGED = 120

TIMELINE_STATE_CHANGED = 112
EDITOR_WINDOW_STATE_CHANGED = 113
ALL_STATES_CHANGED = 120


# sequencer #
BPM_CHANGED = 200
LPB_CHANGED = 201
LENGTH_CHANGED = 202
SWING_CHANGED = 203
SCALE_CHANGED = 204
REPEATS_CHANGED = 205


